#端口号
server:
  port: 31001
#spring配置文件
spring:
  application:
    name: xc‐service‐manage‐cms
#mongo配置
  data:
    mongodb:
      uri: mongodb://192.168.1.160:27017
      database: xc_cms
#配置权限控制器
#  security:
#    basic:
#      enabled: false




